Room
int Room::roomNumber
int Room::floor
int Room::size
int Room::num_occupants
Room::Room(const Room &other)
Room::Room(const Room &&other)
Room::Room(int roomNumber, int floor, int size)
virtual Room::~Room()
int Room::getRoomNumber() const
Referenced by operator<<.
int Room::getFloor() const
Referenced by operator<<.
int Room::getSize() const
Referenced by operator<<.
bool Room::isOccupied() const
Referenced by operator<<.
int Room::getNumOccupants() const
Referenced by operator<<.
void Room::addOccupant()
Referenced by Staff::Staff, OfficeStaff::~OfficeStaff.
void Room::removeOccupant()
ostream& operator<<(ostream &os, const Room &room)