Turn
long Turn::startTime
Referenced by changeStartTime, Turn.
long Turn::duration
Referenced by changeDuration, Turn.
MedicalStaff* Turn::medicalStaff
Referenced by changeMedicalStaff, Turn.
Patient* Turn::patient
Referenced by changePatient, Turn.
Turn::Turn(MedicalStaff &medicalStaff, Patient &patient, long startTime, long duration)
References duration, medicalStaff, patient, startTime.
Turn::Turn(const Turn &other)
References duration, medicalStaff, patient, startTime.
Turn::Turn(Turn &&other)
References duration, medicalStaff, patient, startTime.
virtual Turn::~Turn()
const long Turn::getStartTime() const
Referenced by operator<<.
const long Turn::getDuration() const
Referenced by operator<<.
const MedicalStaff* Turn::getMedicalStaff() const
Referenced by Clinic::addTurn, operator<<.
const Patient* Turn::getPatient() const
Referenced by operator<<.
void Turn::changeStartTime(long startTime)
References startTime.
void Turn::changeDuration(long duration)
References duration.
void Turn::changeMedicalStaff(MedicalStaff *medicalStaff)
References MedicalStaff::deleteTurn, medicalStaff.
void Turn::changePatient(Patient *patient)
References Patient::deleteTurn, patient.
ostream& operator<<(ostream &os, const Turn &turn)