Address
char* Address::country
Referenced by Address, operator=, setCountry, ~Address.
char* Address::city
Referenced by Address, operator=, setCity, ~Address.
char* Address::street
Referenced by Address, operator=, setStreet, ~Address.
int Address::buildNum
Referenced by Address, operator=.
int Address::floorNum
Referenced by Address, operator=.
int Address::houseNum
Referenced by Address, operator=.
Address::Address(const char *country, const char *city, const char *street, int buildNum, int floorNum, int houseNum)
References buildNum, floorNum, houseNum.
Address::Address(const Address &other)
References buildNum, city, country, floorNum, houseNum, street.
Address::Address(Address &&other)
References buildNum, city, country, floorNum, houseNum, street.
Address::~Address()
References city, country, street.
void Address::operator=(const Address &address)
References buildNum, city, country, floorNum, houseNum, street.
const char* Address::getCountry() const
Referenced by operator<<.
const char* Address::getCity() const
Referenced by operator<<.
const char* Address::getStreet() const
Referenced by operator<<.
int Address::getBuildNO() const
Referenced by operator<<.
int Address::getFloor() const
Referenced by operator<<.
int Address::getHouseNO() const
Referenced by operator<<.
void Address::setCountry(const char *country)
References country.
void Address::setCity(const char *city)
References city.
void Address::setStreet(const char *street)
References street.
void Address::setBuildNum(int floor)
void Address::setFloorNum(int floor)
void Address::setHouseNum(int houseNum)
ostream& operator<<(ostream &os, const Address &add)