Nurse
const int Nurse::MAX_NURSE_SERVICES
Referenced by addServices, Nurse.
char** Nurse::services
Referenced by addServices, Nurse, operator=, toOs, ~Nurse.
int Nurse::num_services
Referenced by addServices, Nurse, operator=, toOs, ~Nurse.
Nurse::Nurse(Nurse &&other)
Nurse::Nurse(MedicalStaff &&medicalStaff, const char *service)
Nurse::Nurse(const MedicalStaff &medicalStaff, const char *service)
References MAX_NURSE_SERVICES, num_services, services.
Nurse::Nurse(const Nurse &other)
References getNumServices, getServices, num_services, services.
Nurse::~Nurse()
References num_services, services.
const Nurse & Nurse::operator=(const Nurse &nurse)
References getNumServices, getServices, num_services, services.
char** Nurse::getServices() const
Referenced by Nurse, operator=.
void Nurse::addServices(const char *service)
References MAX_NURSE_SERVICES, num_services, services.
int Nurse::getNumServices() const
Referenced by Nurse, operator=.
void Nurse::toOs(ostream &os) const override
References num_services, services, MedicalStaff::toOs.