Patient
const int Patient::MAX_TURNS_SIZE
Referenced by addTurn, deleteTurn, Patient.
Turn** Patient::turns
Referenced by addTurn, deleteTurn, Patient, ~Patient.
Doctor* Patient::personalDoctor
Referenced by changeDoctor, Patient, toOs.
int Patient::numTurns
Referenced by addTurn, deleteTurn, Patient.
bool Patient::isSick
Referenced by answerCall, Patient.
Patient::Patient(const Person &person, Doctor &personalDoctor, bool sick=false)
References isSick, MAX_TURNS_SIZE, numTurns, personalDoctor, turns.
Patient::Patient(Patient &other)
References isSick, MAX_TURNS_SIZE, numTurns, personalDoctor, turns.
Patient::~Patient()
References turns.
void Patient::operator=(const Patient &patient)
int Patient::answerCall()
References isSick.
Referenced by Secretary::callPatient.
void Patient::changeDoctor(Doctor &doctor)
References personalDoctor.
void Patient::changeClinicMember(bool clinicMember)
int Patient::getNumTurns()
void Patient::addTurn(Turn &turn)
References MAX_TURNS_SIZE, numTurns, turns.
void Patient::deleteTurn(Turn &turn)
References MAX_TURNS_SIZE, numTurns, turns.
Referenced by Turn::changePatient.
void Patient::toOs(ostream &os) const override
References Person::getName, personalDoctor, Person::toOs.
Doctor* Patient::getPersonalDoctor() const
Referenced by Secretary::callPatient.
void Patient::setPersonalDoctor(Doctor &doctor)
bool Patient::getIsSick() const
void Patient::setIsSick(const bool sick)