MedicalStaff
const int MedicalStaff::TURN_SIZE
Referenced by addTurn, deleteTurn, MedicalStaff, operator=.
long MedicalStaff::acceptHoursFrom
Referenced by MedicalStaff, operator=, toOs.
long MedicalStaff::acceptHoursTo
Referenced by MedicalStaff, operator=, toOs.
Room* MedicalStaff::room
Turn** MedicalStaff::turns
Referenced by addTurn, deleteTurn, MedicalStaff, operator=, operator[], ~MedicalStaff.
int MedicalStaff::turnsNumber
Referenced by addTurn, deleteTurn, MedicalStaff, operator=.
MedicalStaff::MedicalStaff(const Person &person, long extension, long salary, long acceptHoursFrom, long acceptHoursTo, Room &room)
References acceptHoursFrom, acceptHoursTo, TURN_SIZE, turns, turnsNumber.
MedicalStaff::MedicalStaff(const MedicalStaff &other)
References acceptHoursFrom, acceptHoursTo, TURN_SIZE, turns, turnsNumber.
MedicalStaff::~MedicalStaff()
References turns.
void MedicalStaff::operator=(const MedicalStaff &medicalstaff)
References acceptHoursFrom, acceptHoursTo, TURN_SIZE, turns, turnsNumber.
long MedicalStaff::getNextFreeTime(long duration) const
Referenced by Secretary::callPatient.
void MedicalStaff::addTurn(Turn &turn) const
References TURN_SIZE, turns, turnsNumber.
Referenced by Clinic::addTurn.
void MedicalStaff::deleteTurn(const Turn &turn)
References TURN_SIZE, turns, turnsNumber.
Referenced by Turn::changeMedicalStaff.
Turn * MedicalStaff::operator[](int index)
References turns.
void MedicalStaff::toOs(ostream &os) const override
References acceptHoursFrom, acceptHoursTo, Staff::toOs.
Referenced by Doctor::toOs, Nurse::toOs.