ClinicManager
const int ClinicManager::STAFF_SIZE
Clinic* ClinicManager::clinic
Referenced by ClinicManager, fireStaff, hireStaff, setClinic.
ClinicManager::ClinicManager(const OfficeStaff &&officeStaff, const Doctor &&doctor)
ClinicManager::ClinicManager(const OfficeStaff &officeStaff, const Doctor &doctor)
ClinicManager::ClinicManager(const ClinicManager &other)
References clinic.
virtual ClinicManager::~ClinicManager()
void ClinicManager::setClinic(Clinic *new_clinic)
References clinic, Clinic::setClinicManager.
Referenced by Clinic::setClinicManager.
void ClinicManager::fireStaff(const Staff &staff) const
References clinic, Clinic::removeStaff.
Referenced by main.
void ClinicManager::hireStaff(Staff &staff) const
References Clinic::addStaff, clinic.
Referenced by main.
void ClinicManager::toOs(ostream &os) const override
References Doctor::toOs.