Person
eGender
int Person::id
Referenced by Person.
char* Person::name
Referenced by Secretary::callPatient, Person, ~Person.
char* Person::phone
Referenced by Person, setPhone, ~Person.
int Person::age
Referenced by Person.
Address Person::address
Referenced by setAddress.
eGender Person::gender
Referenced by displayGender, Person.
Person::Person(int id, const char *name, const char *phone, int age, const Address &address, const eGender &gender)
References age, gender, id.
Person::Person(const Person &other)
References age, gender, id, name, phone.
Person::Person(Person &&other)
References age, gender, name, phone.
Person::~Person()
References name, phone.
int Person::getId() const
Referenced by toOs.
const char* Person::getName() const
Referenced by Secretary::callPatient, operator<<, Patient::toOs, toOs.
const char* Person::getPhone() const
Referenced by toOs.
const int Person::getAge() const
Referenced by toOs.
const eGender Person::getGender() const
const Address& Person::getAddress() const
Referenced by toOs.
void Person::setPhone(const char *phone)
References phone.
void Person::setAddress(Address &address)
References address.
void Person::toOs(ostream &os) const
References displayGender, getAddress, getAge, getId, getName, getPhone.
Referenced by operator<<, Staff::toOs, Patient::toOs.
const char * Person::displayGender() const
References Female, gender, Male.
Referenced by toOs.
ostream& operator<<(ostream &os, const Person &person)