Staff
long Staff::extension
Referenced by toOs.
long Staff::salary
Referenced by toOs.
Room* Staff::room
Referenced by OfficeStaff::OfficeStaff, Staff, toOs, OfficeStaff::~OfficeStaff.
Clinic* Staff::clinic
Staff::Staff(const Person &person, long extension, long salary, Room &room)
References Room::addOccupant, room.
Staff::Staff(const Staff &staff)
References room.
Staff::Staff(Staff &&staff)
virtual Staff::~Staff()
long Staff::getExtension() const
long Staff::getSalary() const
const Clinic* Staff::getClinic() const
void Staff::setSalary(long salary)
void Staff::setClinic(Clinic *clinic)
Referenced by Clinic::setStaff.
void Staff::toOs(ostream &os) const override
References extension, room, salary, Person::toOs.
Referenced by OfficeStaff::toOs, MedicalStaff::toOs.