Clinic
const int Clinic::MAX_NUM_ROOMS
Referenced by addRoom, Clinic, printRooms, removeRoom.
const int Clinic::MAX_NUM_STAFF
Referenced by addStaff, Clinic, getSecretary, printStaff, removeStaff.
const int Clinic::MAX_NUM_PATIENTS
Referenced by addPatient, Clinic, printPatients, removePatient.
const int Clinic::MAX_NUM_TURNS
Referenced by addTurn, Clinic, printTurns, removeTurn.
char* Clinic::name
Referenced by Clinic, ~Clinic.
Address Clinic::address
ClinicManager* Clinic::manager
Referenced by Clinic, setClinicManager.
Room** Clinic::rooms
Referenced by addRoom, Clinic, printRooms, removeRoom, ~Clinic.
int Clinic::numRooms
Referenced by addRoom, Clinic, printRooms, removeRoom.
Staff** Clinic::staff
Referenced by addStaff, Clinic, getSecretary, printStaff, ~Clinic.
int Clinic::numStaff
Referenced by addStaff, Clinic, printStaff, removeStaff.
Patient** Clinic::patients
Referenced by addPatient, Clinic, printPatients, removePatient, ~Clinic.
int Clinic::numPatients
Referenced by addPatient, Clinic, printPatients, removePatient.
Turn** Clinic::turns
Referenced by addTurn, Clinic, printTurns, removeTurn, ~Clinic.
int Clinic::numTurns
Referenced by addTurn, Clinic, printTurns, removeTurn.
Clinic::Clinic(const char *name, const Address &address)
References manager, MAX_NUM_PATIENTS, MAX_NUM_ROOMS, MAX_NUM_STAFF, MAX_NUM_TURNS, numPatients, numRooms, numStaff, numTurns, patients, rooms, staff, turns.
Clinic::Clinic(const Clinic &other)
References manager, MAX_NUM_PATIENTS, MAX_NUM_ROOMS, MAX_NUM_STAFF, MAX_NUM_TURNS, name, numPatients, numRooms, numStaff, numTurns, patients, rooms, staff, turns.
Clinic::~Clinic()
References name, patients, rooms, setClinicManager, staff, turns.
void Clinic::addStaff(Staff *staff)
References MAX_NUM_STAFF, numStaff, setStaff, staff.
Referenced by ClinicManager::hireStaff, setClinicManager.
void Clinic::removeStaff(const Staff &staff)
References MAX_NUM_STAFF, numStaff.
Referenced by ClinicManager::fireStaff, setClinicManager.
void Clinic::addPatient(Patient &patient)
References MAX_NUM_PATIENTS, numPatients, patients.
Referenced by main.
void Clinic::removePatient(const Patient &patient)
References MAX_NUM_PATIENTS, numPatients, patients.
Referenced by main.
void Clinic::callPatient(const Patient &patient)
void Clinic::getAvailableTurn(const Patient &patient)
void Clinic::addRoom(Room &room)
References MAX_NUM_ROOMS, numRooms, rooms.
Referenced by main.
void Clinic::removeRoom(const Room &room)
References MAX_NUM_ROOMS, numRooms, rooms.
Referenced by main.
void Clinic::addTurn(Turn &turn)
References MedicalStaff::addTurn, Turn::getMedicalStaff, MAX_NUM_TURNS, numTurns, turns.
void Clinic::removeTurn(const Turn &turn)
References MAX_NUM_TURNS, numTurns, turns.
void Clinic::updateTurn(const Turn &oldturn, const Turn &newturn)
void Clinic::setStaff(Staff **old_staff, Staff *new_staff)
References Staff::setClinic.
Referenced by addStaff.
const char* Clinic::getName() const
Referenced by operator<<.
const Address& Clinic::getAddress() const
Referenced by operator<<.
const ClinicManager* Clinic::getManager() const
Referenced by operator<<.
void Clinic::printStaff(ostream &os) const
References MAX_NUM_STAFF, numStaff, staff.
Referenced by operator<<.
void Clinic::printPatients(ostream &os) const
References MAX_NUM_PATIENTS, numPatients, patients.
Referenced by operator<<.
void Clinic::printRooms(ostream &os) const
References MAX_NUM_ROOMS, numRooms, rooms.
Referenced by operator<<.
void Clinic::printTurns(ostream &os) const
References MAX_NUM_TURNS, numTurns, turns.
Referenced by operator<<.
void Clinic::setClinicManager(ClinicManager *new_manager)
References addStaff, manager, removeStaff, ClinicManager::setClinic.
Referenced by main, ClinicManager::setClinic, ~Clinic.
Secretary * Clinic::getSecretary() const
References MAX_NUM_STAFF, staff.
Referenced by main.
ostream& operator<<(ostream &os, const Clinic &clinic)